/* Copyright 2023 Google LLC. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/
// DISCLAIMER: This file was generated by Gemini.

import * as fs from 'fs';
import * as path from 'path';
import * as d3 from 'd3';
import { JSDOM } from 'jsdom';

// --- Data Structures ---
interface Metric {
    loss: number;
    step: number;
    accuracy?: number;
    klDivergence?: number;
    alphaFirstParams?: number[];
    alphaSecondParams?: number[];
    [key: string]: number | number[] | undefined;
}

type ExperimentData = [string, Metric[]][]; // [ExperimentName, MetricsOverSteps[]]

// Define available metrics
const SCALAR_METRICS = ['loss', 'accuracy', 'klDivergence'] as const;
const ARRAY_METRICS = ['alphaFirstParams', 'alphaSecondParams'] as const;
type ScalarMetric = typeof SCALAR_METRICS[number];
type ArrayMetric = typeof ARRAY_METRICS[number];
type AnyMetric = ScalarMetric | ArrayMetric;

// Type for transformed data points used for plotting
type PlotPoint = { step: number; value: number };
// Type for data structure passed to the generic plotting function
// [LegendKey (string or number), PlotPoints[]]
type PlotData = [string | number, PlotPoint[]][];


// --- Plotting Configuration ---
const config = {
    width: 650,
    height: 400,
    margin: { top: 50, right: 180, bottom: 60, left: 60 }, // Increased top margin for title
    axisLabelFontSize: '12px',
    tickFontSize: '10px',
    titleFontSize: '14px', // Slightly smaller title for potentially long auto-generated titles
    legendFontSize: '10px',
    lineWidth: 1.5,
    fontFamily: 'Helvetica Neue, Helvetica, Arial, sans-serif',
    gridColor: '#e0e0e0',
    axisColor: '#333333',
    labelColor: '#000000',
};


// --- Generic Plotting Function ---
/**
 * Creates a NeurIPS-style line plot from pre-processed data.
 * @param plotData Data formatted as [LegendKey, {step, value}[]][].
 * @param outputFilePath Path to save the generated SVG file.
 * @param plotTitle Title for the plot.
 * @param xAxisLabel Label for the X-axis.
 * @param yAxisLabel Label for the Y-axis.
 */
function createPlot(
    plotData: PlotData,
    outputFilePath: string,
    plotTitle: string,
    xAxisLabel: string,
    yAxisLabel: string
): void {
    // --- JSDOM Setup ---
    const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
    const body = d3.select(dom.window.document.body);

    // --- SVG Canvas Setup ---
    const plotWidth = config.width - config.margin.left - config.margin.right;
    const plotHeight = config.height - config.margin.top - config.margin.bottom;
    const svg = body.append('svg')
        .attr('width', config.width)
        .attr('height', config.height)
        .attr('xmlns', 'http://www.w3.org/2000/svg')
        .style('font-family', config.fontFamily)
        .style('background-color', 'white');
    svg.append('rect').attr('width', '100%').attr('height', '100%').attr('fill', 'white');
    const plotArea = svg.append('g')
        .attr('transform', `translate(${config.margin.left},${config.margin.top})`);

    // Check if data is empty after potential filtering upstream
    if (plotData.length === 0) {
        console.warn(`⚠️ Warning: No data provided to createPlot function for ${outputFilePath}. Plot will be empty.`);
        svg.append("text").attr("x", config.width / 2).attr("y", config.height / 2).attr("text-anchor", "middle")
            .text("No data to plot.");
        try {
            // Ensure directory exists before writing empty plot
            fs.mkdirSync(path.dirname(outputFilePath), { recursive: true });
            fs.writeFileSync(outputFilePath, body.html());
        } catch (err) { console.error(`❌ Error writing empty SVG:`, err); }
        return;
    }

    // --- Scales ---
    const allSteps = plotData.flatMap(([_, points]) => points.map(p => p.step));
    const allYValues = plotData.flatMap(([_, points]) => points.map(p => p.value));
    let xDomain = d3.extent(allSteps) as [number, number];
    let yDomain = d3.extent(allYValues) as [number, number];
    if (!xDomain) xDomain = [0, 1];
    else if (xDomain[0] === xDomain[1]) xDomain = [xDomain[0] - 0.5, xDomain[1] + 0.5];
    if (!yDomain) yDomain = [0, 1];
    else if (yDomain[0] === yDomain[1]) yDomain = [yDomain[0] - Math.abs(yDomain[0] * 0.1 || 0.5), yDomain[1] + Math.abs(yDomain[1] * 0.1 || 0.5)];

    const xScale = d3.scaleLinear().domain(xDomain).range([0, plotWidth]).nice();
    const yScale = d3.scaleLinear().domain(yDomain).range([plotHeight, 0]).nice();
    const colorScale = d3.scaleOrdinal(d3.schemeCategory10)
        .domain(plotData.map(([key, _]) => String(key)));

    // --- Axes ---
    const xAxisGenerator = d3.axisBottom(xScale);
    const xAxis = plotArea.append('g').attr('class', 'x-axis').attr('transform', `translate(0,${plotHeight})`)
        .call(xAxisGenerator).style('font-size', config.tickFontSize).style('color', config.axisColor);
    xAxis.select('.domain').remove();
    xAxis.selectAll('.tick line').attr('stroke', config.gridColor).attr('stroke-dasharray', '2,2').attr('y1', -plotHeight).attr('y2', 0);

    const yAxisGenerator = d3.axisLeft(yScale);
    const yAxis = plotArea.append('g').attr('class', 'y-axis')
        .call(yAxisGenerator).style('font-size', config.tickFontSize).style('color', config.axisColor);
    yAxis.select('.domain').remove();
    yAxis.selectAll('.tick line').attr('stroke', config.gridColor).attr('stroke-dasharray', '2,2').attr('x1', 0).attr('x2', plotWidth);
    yAxis.selectAll('.tick text').attr('x', -5);

    // --- Axis Labels ---
    svg.append('text').attr('class', 'x-axis-label').attr('x', config.margin.left + plotWidth / 2).attr('y', config.height - config.margin.bottom / 2 + 10)
        .attr('text-anchor', 'middle').style('font-size', config.axisLabelFontSize).style('fill', config.labelColor).text(xAxisLabel);
    svg.append('text').attr('class', 'y-axis-label').attr('transform', 'rotate(-90)').attr('x', -(config.margin.top + plotHeight / 2)).attr('y', config.margin.left / 2 - 15)
        .attr('text-anchor', 'middle').style('font-size', config.axisLabelFontSize).style('fill', config.labelColor).text(yAxisLabel);

    // --- Plot Title ---
    svg.append('text').attr('class', 'plot-title').attr('x', config.width / 2).attr('y', config.margin.top / 2)
        .attr('text-anchor', 'middle').style('font-size', config.titleFontSize).style('fill', config.labelColor).style('font-weight', 'bold').text(plotTitle);

    // --- Line Generator ---
    const lineGenerator = d3.line<PlotPoint>()
        .x(d => xScale(d.step))
        .y(d => yScale(d.value))
        .defined(d => !isNaN(d.value) && d.value !== null)
        .curve(d3.curveLinear);

    // --- Draw Lines ---
    plotArea.selectAll('.line')
        .data(plotData)
        .enter()
        .append('path')
        .attr('class', 'line')
        .attr('d', ([_, points]) => lineGenerator(points))
        .style('fill', 'none')
        .style('stroke', ([key, _]) => colorScale(String(key)))
        .style('stroke-width', config.lineWidth);

    // --- Legend ---
    const legend = svg.append('g').attr('class', 'legend')
        .attr('transform', `translate(${config.width - config.margin.right + 20}, ${config.margin.top})`);
    const legendItems = legend.selectAll('.legend-item')
        .data(plotData)
        .enter()
        .append('g')
        .attr('class', 'legend-item')
        .attr('transform', (d, i) => `translate(0, ${i * 20})`);
    legendItems.append('line').attr('x1', 0).attr('x2', 20).attr('y1', 5).attr('y2', 5)
        .style('stroke', ([key, _]) => colorScale(String(key))).style('stroke-width', config.lineWidth * 1.5);
    legendItems.append('text').attr('x', 25).attr('y', 9)
        .text(([key, _]) => String(key))
        .style('font-size', config.legendFontSize).style('fill', config.labelColor);

    // --- Output SVG to File ---
    try {
        // Ensure directory exists before writing
        fs.mkdirSync(path.dirname(outputFilePath), { recursive: true });
        const svgOutput = body.html();
        fs.writeFileSync(outputFilePath, svgOutput);
    } catch (err) {
        console.error(`❌ Error writing SVG file to ${outputFilePath}:`, err);
    }
}


// --- Data Preparation & Plotting Functions ---

/** Plots a scalar metric (loss, accuracy, klDivergence) */
function plotScalarMetric(
    experimentData: ExperimentData,
    metric: ScalarMetric,
    outputDir: string // Base directory for the experiment set
): boolean {
    console.log(`⏳ Preparing plot for scalar metric "${metric}"...`);
    const plotData: PlotData = [];

    for (const [expName, metrics] of experimentData) {
        const points: PlotPoint[] = [];
        for (const m of metrics) {
            const value = m[metric];
            if (typeof value === 'number' && !isNaN(value)) {
                points.push({ step: m.step, value: value });
            }
        }
        if (points.length > 0) {
            plotData.push([expName, points]);
        }
    }

    if (plotData.length === 0) {
        console.log(`ℹ️ No valid data found for metric "${metric}". Skipping plot.`);
        return false;
    }

    // Save directly in the outputDir
    const outputFilePath = path.join(outputDir, `plot_${metric}.svg`);
    const plotTitle = `${metric.charAt(0).toUpperCase() + metric.slice(1)} vs. Step`;
    const yAxisLabel = metric.charAt(0).toUpperCase() + metric.slice(1);

    createPlot(plotData, outputFilePath, plotTitle, 'Step', yAxisLabel);
    console.log(`✅ Scalar plot for "${metric}" saved to ${outputFilePath}`);
    return true;
}


/** Plots a specific layer index of an array metric across all experiments */
function plotLayerMetric(
    experimentData: ExperimentData,
    metric: ArrayMetric,
    layerIndex: number,
    outputDir: string // Specific output directory (e.g., .../layer_plots)
): boolean {
    // console.log(`⏳ Preparing plot for metric "${metric}", Layer Index ${layerIndex}...`); // Logged by caller in 'all' mode
    const plotData: PlotData = [];

    if (layerIndex < 0) {
        console.error(`❌ Invalid layer index: ${layerIndex}. Index must be non-negative.`);
        return false;
    }

    let maxLayersFound = -1; // Track max layers to validate index later

    for (const [expName, metrics] of experimentData) {
        const points: PlotPoint[] = [];
        for (const m of metrics) {
            const arr = m[metric];
            if (Array.isArray(arr)) {
                maxLayersFound = Math.max(maxLayersFound, arr.length - 1);
                if (layerIndex < arr.length) {
                    const value = arr[layerIndex];
                    if (typeof value === 'number' && !isNaN(value)) {
                        points.push({ step: m.step, value: value });
                    }
                }
            }
        }
        if (points.length > 0) {
            plotData.push([expName, points]);
        }
    }

    if (layerIndex > maxLayersFound && maxLayersFound !== -1) {
        console.error(`❌ Invalid layer index: ${layerIndex}. Maximum index found in data for "${metric}" is ${maxLayersFound}.`);
        return false; // Should not happen if maxLayers calculated correctly before loop
    }
    if (plotData.length === 0) {
        // Don't log skipping message here if called from 'all' loop, let the caller handle summary
        // console.log(`ℹ️ No valid data found for metric "${metric}" at Layer Index ${layerIndex}. Skipping plot.`);
        return false;
    }


    // Save in the specific layer_plots directory
    const outputFilePath = path.join(outputDir, `plot_${metric}_layer_${layerIndex}.svg`);
    const plotTitle = `${metric} - Layer ${layerIndex} vs. Step`;
    const yAxisLabel = `${metric}[${layerIndex}]`;

    createPlot(plotData, outputFilePath, plotTitle, 'Step', yAxisLabel);
    console.log(`✅ Layer plot for "${metric}" Layer ${layerIndex} saved to ${outputFilePath}`);
    return true;
}


/** Plots all layer indices for one or all experiments for an array metric */
function plotExperimentMetric(
    experimentData: ExperimentData,
    metric: ArrayMetric,
    targetExperimentName: string | undefined,
    outputDir: string // Specific output directory (e.g., .../experiment_plots)
): number { // Return number of plots generated

    const experimentsToPlot: [string, Metric[]][] = targetExperimentName
        ? experimentData.filter(([name, _]) => name === targetExperimentName)
        : experimentData;

    if (targetExperimentName && experimentsToPlot.length === 0) {
        console.error(`❌ Experiment "${targetExperimentName}" not found in the data.`);
        return 0;
    }
    if (experimentsToPlot.length === 0) {
        console.log(`ℹ️ No experiments found in the data.`);
        return 0;
    }

    // console.log(`⏳ Preparing plot(s) for metric "${metric}" by experiment...`); // Logged by caller in 'all' mode
    let plotsGenerated = 0;

    for (const [expName, metrics] of experimentsToPlot) {
        const plotData: PlotData = [];
        let maxLayers = 0;

        for (const m of metrics) { // Find max layers for this specific experiment
            const arr = m[metric];
            if (Array.isArray(arr)) {
                maxLayers = Math.max(maxLayers, arr.length);
            }
        }

        if (maxLayers === 0) {
            // console.log(`ℹ️ Metric "${metric}" not found or always empty for experiment "${expName}". Skipping plot.`);
            continue;
        }

        for (let layerIndex = 0; layerIndex < maxLayers; layerIndex++) { // Prepare data for each layer
            const points: PlotPoint[] = [];
            for (const m of metrics) {
                const arr = m[metric];
                if (Array.isArray(arr) && layerIndex < arr.length && typeof arr[layerIndex] === 'number' && !isNaN(arr[layerIndex])) {
                    points.push({ step: m.step, value: arr[layerIndex] });
                }
            }
            if (points.length > 0) {
                plotData.push([`Layer ${layerIndex}`, points]);
            }
        }


        if (plotData.length === 0) {
            // console.log(`ℹ️ No valid layer data found for metric "${metric}" in experiment "${expName}". Skipping plot.`);
            continue;
        }

        // Save in the specific experiment_plots directory
        const outputFilePath = path.join(outputDir, `plot_${metric}_exp_${expName.replace(/[^a-z0-9]/gi, '_')}.svg`);
        const plotTitle = `${metric} vs. Step for Experiment: ${expName}`;
        const yAxisLabel = `${metric} Value (Legend=Layer Index)`;

        createPlot(plotData, outputFilePath, plotTitle, 'Step', yAxisLabel);
        console.log(`✅ Experiment plot for "${metric}" Experiment "${expName}" saved to ${outputFilePath}`);
        plotsGenerated++;
    }
    // Summary log handled by caller in 'all' mode
    return plotsGenerated;
}


// --- Argument Parsing Helper ---
function parseArgs(args: string[]): { [key: string]: string | number | boolean } {
    const parsed: { [key: string]: string | number | boolean } = {};
    for (let i = 0; i < args.length; i++) {
        if (args[i].startsWith('--')) {
            const key = args[i].substring(2);
            const nextVal = args[i + 1];
            if (nextVal && !nextVal.startsWith('--')) {
                const numVal = parseFloat(nextVal);
                parsed[key] = isNaN(numVal) ? nextVal : numVal;
                i++;
            } else {
                parsed[key] = true;
            }
        }
    }
    return parsed;
}

// --- Helper to find Max Layer Index ---
function findMaxLayerIndex(experimentData: ExperimentData, metric: ArrayMetric): number {
    let maxIndex = -1;
    for (const [_, metrics] of experimentData) {
        for (const m of metrics) {
            const arr = m[metric];
            if (Array.isArray(arr)) {
                maxIndex = Math.max(maxIndex, arr.length - 1);
            }
        }
    }
    return maxIndex;
}


// --- Main Execution Logic ---
const rawArgs = process.argv.slice(2);

// Updated Usage Message
const usage = `❌ Invalid arguments.
Usage:
  Scalar:    ts-node src/plotter.ts <experiment_set_name> <loss|accuracy|klDivergence>
  All:       ts-node src/plotter.ts <experiment_set_name> all
             (Plots all scalar metrics, plus all layer/experiment plots for array metrics into subdirs)
  Layer:     ts-node src/plotter.ts <experiment_set_name> <array_metric> --mode layer --layer-index <index> [--output-dir <dir>]
  Exp.:      ts-node src/plotter.ts <experiment_set_name> <array_metric> --mode experiment [--experiment-name <name>] [--output-dir <dir>]

Default output dirs for array plots: <experiment_set_name>/[layer_plots|experiment_plots]/
Use --output-dir to override *specific* plot output location (mainly for non-'all' calls).`;


if (rawArgs.length < 2) {
    console.error(usage);
    process.exit(1);
}

const experimentSetName = rawArgs[0];
const metricArg = rawArgs[1]; // Can be a specific metric or 'all'
const options = parseArgs(rawArgs.slice(2)); // Parse options like --mode, --layer-index

// --- Path Construction ---
const baseExperimentDir = path.resolve(experimentSetName); // Base directory for the experiment set
const inputJsonPath = path.join(baseExperimentDir, 'metrics.json');

// --- Read and Parse Input Data ---
let experimentData: ExperimentData;
try {
    if (!fs.existsSync(baseExperimentDir) || !fs.lstatSync(baseExperimentDir).isDirectory()) {
        throw new Error(`Experiment directory not found or is not a directory: ${baseExperimentDir}`);
    }
    if (!fs.existsSync(inputJsonPath)) {
        throw new Error(`Input file 'metrics.json' not found inside directory: ${baseExperimentDir}`);
    }
    const jsonData = fs.readFileSync(inputJsonPath, 'utf-8');
    experimentData = JSON.parse(jsonData);
    if (!Array.isArray(experimentData) || experimentData.some(item => !Array.isArray(item) || item.length !== 2 || typeof item[0] !== 'string' || !Array.isArray(item[1]))) {
        throw new Error("Invalid JSON structure in 'metrics.json'. Expected format: [string, Metric[]][]");
    }
} catch (error: any) {
    console.error(`❌ Error reading or parsing JSON file "${inputJsonPath}":`, error.message);
    process.exit(1);
}

// --- Route to appropriate plotting function ---
try {
    let totalPlotsGenerated = 0;

    if (metricArg.toLowerCase() === 'all') {
        console.log(`✨ Processing 'all' metrics for experiment set: ${experimentSetName}`);
        console.warn("⚠️ This may generate a large number of plot files!");

        // --- Plot Scalar Metrics ---
        console.log("\n⏳ Plotting scalar metrics...");
        let scalarPlotsGenerated = 0;
        for (const scalarMetric of SCALAR_METRICS) {
            // Output dir for scalar is the base experiment dir
            if (plotScalarMetric(experimentData, scalarMetric, baseExperimentDir)) {
                scalarPlotsGenerated++;
            }
        }
        console.log(`  > Generated ${scalarPlotsGenerated} scalar plot(s).`);
        totalPlotsGenerated += scalarPlotsGenerated;

        // --- Plot Array Metrics (Layer and Experiment) ---
        for (const arrayMetric of ARRAY_METRICS) {
            console.log(`\n⏳ Plotting array metric "${arrayMetric}"...`);

            // Find max layer index for this metric
            const maxLayerIndex = findMaxLayerIndex(experimentData, arrayMetric);
            if (maxLayerIndex < 0) {
                console.log(`  ℹ️ Metric "${arrayMetric}" not found or has no layer data. Skipping layer/experiment plots.`);
                continue;
            }

            // Define output directories
            const layerPlotsDir = path.join(baseExperimentDir, 'layer_plots');
            const experimentPlotsDir = path.join(baseExperimentDir, 'experiment_plots');

            // Generate Layer Plots
            console.log(`  Generating layer plots (up to index ${maxLayerIndex}) into ${layerPlotsDir}...`);
            let layerPlotsGenerated = 0;
            for (let i = 0; i <= maxLayerIndex; i++) {
                if (plotLayerMetric(experimentData, arrayMetric, i, layerPlotsDir)) {
                    layerPlotsGenerated++;
                }
            }
            console.log(`    > Generated ${layerPlotsGenerated} layer plot(s) for "${arrayMetric}".`);
            totalPlotsGenerated += layerPlotsGenerated;

            // Generate Experiment Plots
            console.log(`  Generating experiment plots into ${experimentPlotsDir}...`);
            const experimentPlotsGenerated = plotExperimentMetric(experimentData, arrayMetric, undefined, experimentPlotsDir);
            console.log(`    > Generated ${experimentPlotsGenerated} experiment plot(s) for "${arrayMetric}".`);
            totalPlotsGenerated += experimentPlotsGenerated;
        }

    } else if (SCALAR_METRICS.includes(metricArg as ScalarMetric)) {
        // Plot specific scalar metric to base dir
        const outputDir = options['output-dir'] as string || baseExperimentDir;
        if (plotScalarMetric(experimentData, metricArg as ScalarMetric, outputDir)) {
            totalPlotsGenerated++;
        }

    } else if (ARRAY_METRICS.includes(metricArg as ArrayMetric)) {
        const metric = metricArg as ArrayMetric;
        const mode = options['mode'];

        if (mode === 'layer') {
            const layerIndex = options['layer-index'];
            if (typeof layerIndex !== 'number' || layerIndex < 0 || !Number.isInteger(layerIndex)) {
                throw new Error("Missing or invalid --layer-index <non-negative integer> for --mode layer.");
            }
            // Default output to subdir, allow override
            const defaultOutputDir = path.join(baseExperimentDir, 'layer_plots');
            const outputDir = options['output-dir'] as string || defaultOutputDir;
            if (plotLayerMetric(experimentData, metric, layerIndex, outputDir)) {
                totalPlotsGenerated++;
            }
        } else if (mode === 'experiment') {
            const targetExpName = options['experiment-name'] as string | undefined;
            if (targetExpName !== undefined && typeof targetExpName !== 'string') {
                throw new Error("Invalid --experiment-name value. Must be a string.");
            }
            // Default output to subdir, allow override
            const defaultOutputDir = path.join(baseExperimentDir, 'experiment_plots');
            const outputDir = options['output-dir'] as string || defaultOutputDir;
            totalPlotsGenerated += plotExperimentMetric(experimentData, metric, targetExpName, outputDir);
        } else {
            throw new Error(`Missing or invalid --mode <layer|experiment> for array metric "${metric}".`);
        }
    } else {
        throw new Error(`Invalid metric specified: "${metricArg}". Use 'all', a scalar metric (${SCALAR_METRICS.join(', ')}), or an array metric (${ARRAY_METRICS.join(', ')}) with appropriate options.`);
    }

    console.log(`\n✨ Plotting process completed. ${totalPlotsGenerated} total plot(s) generated.`);

} catch (error: any) {
    console.error(`\n❌ An error occurred during plotting: ${error.message}`);
    console.log(`\n${usage}`); // Show usage on error
    process.exit(1);
}
